spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}:${SPRING_DATASOURCE_PORT}?&serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081